### ISSUE TITLE
Update checkout action to v4 to avoid node deprecation (and inform downstream)

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubverse-actions#21]
When I was working on #20, I noticed this deprecation warning:

> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

We should update these workflows _and_ inform the downstream repositories that they also need to update their workflows.

**Comment by annakrystalli** [comment]
Sure thing. 

Once updated, you could send your first email to the community through our mailing list if you wanted! 😃

Once our workflows have been updated, folks can use [`hubCI`](https://hubverse-org.github.io/hubCI/) package to re-install the updated versions of workflows.

Also, if we're going to be updating our workflows, what are your thoughts on this [comment](https://github.com/hubverse-org/hubverse-actions/pull/20#discussion_r1701364395) I added to the #20 PR review?

> Follow up question regarding installing our packages in workflows. Until they are on CRAN but given we now have an r-universe, should we be using that to install from instead of GitHub for the time being?

If we want to change the source of our packages, might be a good opportunity to do so.
