### ISSUE TITLE
Ubuntu latest removes R from its default installation 

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubverse-actions#30]
## Instructions for Hub Administrators 2024-12-11

If you have not customized your workflows, use [the `hubCI` package](https://hubverse.github.io/hubCI) to update your workflows:

```r
library("hubCI")

use_hub_github_action(name = "validate-submission")
use_hub_github_action(name = "validate-config")
use_hub_github_action(name = "cache-hubeval-deps")
use_hub_github_action(name = "hubverse-aws-upload")
```

## Problem

In https://github.com/actions/runner-images/issues/10636, GitHub announced that the `ubuntu-latest` workflows are removing R.

They are rolling this feature out across runners at the moment: 

> This change will be rolled out over a period of several weeks beginning December 5th and will complete on January 17th, 2025.

## Impact

This means that all validation checks will eventually fail as the update rolls out.  

It has already hit the flu sight repo in https://github.com/cdcepi/FluSight-forecast-hub/pull/1251

I made a PR for them to pin their ubuntu runner: https://github.com/cdcepi/FluSight-forecast-hub/pull/1253

## Solution

The solution is one of two things:

1. pin the ubuntu runner to 22.04 **OR**
2. set `install-r: true` in the setup R step

The benefits of pinning the ubuntu runner to 22.04 is that it will continue to work for another three years (LTS lifecycle). The drawback is that we will _eventually_ have to find a better solution when LTS ends.

The downside of setting `install_r: true` is that it increases the run time of the validation by about a minute. This is primarily an issue for submission turnover and not of cost since the runner minutes on public repositories do not count against allocated minutes.

**Comment by zkamvar** [comment]
Note that this does not affect our package repositories because we already install the latest version of R by default.

**Comment by annakrystalli** [comment]
Noting that this issue (https://github.com/hubverse-org/hubValidations/issues/57) also exists and might be worth bumping up the priority ladder and benchmarking against the above options.

This option is also a potential: https://github.com/eddelbuettel/github-actions/tree/master/r2u-setup

**Comment by zkamvar** [comment]
> Note that if a hub is using the vanilla workflow, hub admins or team members on forks needing to update their workflow can use `hubCI::use_hub_github_action("validate-submission")` to update their workflow to the latest version

Oh we should make a release first, no?

**Comment by zkamvar** [comment]
I'll go ahead and do that.

**Comment by annakrystalli** [comment]
Oh yeah good call!

**Comment by zkamvar** [comment]
done!

**Comment by zkamvar** [comment]
I'm going to close this issue as it has been addressed and communicated.
